### ISSUE TITLE
希望增加杭州电子科技大学

### ISSUE THREAD

**Issue by LambdaYH** [jeffreystoke/openct-school-info#25]
{
    "name":"杭州电子科技大学",
    "cmsSys":"zfsoft",
    "cmsURL":"http://jxgl.hdu.edu.cn",
    "libSys":"custom",
    "libURL":"http://222.29.81.175/350400/"
  },

**Comment by jeffreystoke** [comment]
已添加, 需要更新学校列表才能获取
